# Base image
FROM golang:1.23-alpine AS base

# Set the working directory
WORKDIR /app

# Install necessary dependencies and Air
RUN apk add --no-cache gcc musl-dev dumb-init \
    && go install github.com/cosmtrek/air@v1.40.4


# Copy only the dependency files for better caching
COPY go.mod go.sum ./
RUN go mod download

# Expose the development port
EXPOSE 9009

# Use dumb-init to handle signals properly
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

# Default command to run Air for live reload
CMD ["air", "-c", ".air.toml"]
