CREATE TABLE public.notifications (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    status INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);