// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"riz.it/domped/internal/config"
	"riz.it/domped/internal/delivery"
	"riz.it/domped/internal/delivery/controller"
	"riz.it/domped/internal/delivery/middleware"
	"riz.it/domped/internal/domain"
	"riz.it/domped/internal/repository"
	"riz.it/domped/internal/usecase"
	"riz.it/domped/internal/util"
)

// Injectors from app.go:

func InitializedApp() *config.App {
	configConfig := config.Get()
	app := config.NewFiber(configConfig)
	jwt := util.NewJWTUtil(configConfig)
	v := middleware.NewAuthMiddleware(jwt)
	logger := config.NewLogger(configConfig)
	db := config.NewDatabase(configConfig, logger)
	userRepository := repository.NewUser(logger)
	walletRepository := repository.NewWallet(logger)
	validate := config.NewValidator(configConfig)
	client := config.NewRedisClient(configConfig)
	email := util.NewEmailUtil(configConfig)
	authUseCase := usecase.NewAuthUseCase(db, logger, userRepository, walletRepository, jwt, validate, client, email)
	authController := controller.NewAuthController(authUseCase, logger)
	transactionRepository := repository.NewTransaction(logger)
	notificationRepository := repository.NewNotification(logger)
	transactionUseCase := usecase.NewTransactionUseCase(db, logger, walletRepository, transactionRepository, notificationRepository, validate, client)
	transactionController := controller.NewTransactionController(transactionUseCase, logger)
	pinRecoveryRepository := repository.NewPinRecovery(logger)
	pinRecoveryUseCase := usecase.NewPinRecoveryUseCase(db, logger, walletRepository, pinRecoveryRepository, validate)
	pinRecoveryController := controller.NewPinRecoveryController(pinRecoveryUseCase, logger)
	notificationUseCase := usecase.NewNotificationUseCase(db, logger, notificationRepository, validate)
	notificationController := controller.NewNotificationController(notificationUseCase, logger)
	midtrans := util.NewMidtransUtil(configConfig)
	topUpRepository := repository.NewTopUp(logger)
	topUpUseCase := usecase.NewTopUpUseCase(db, logger, notificationRepository, midtrans, topUpRepository, walletRepository, transactionRepository, validate)
	topUpController := controller.NewTopUpController(topUpUseCase, logger, midtrans)
	routerConfig := delivery.NewRouter(app, v, authController, transactionController, pinRecoveryController, notificationController, topUpController)
	configApp := config.NewApp(routerConfig, configConfig)
	return configApp
}

// app.go:

var authSet = wire.NewSet(usecase.NewAuthUseCase, controller.NewAuthController)

var userSet = wire.NewSet(repository.NewUser, wire.Bind(new(domain.UserRepository), new(*repository.UserRepository)))

var walletSet = wire.NewSet(repository.NewWallet, wire.Bind(new(domain.WalletRepository), new(*repository.WalletRepository)))

var pinRecoverySet = wire.NewSet(repository.NewPinRecovery, wire.Bind(new(domain.PinRecoveryRepository), new(*repository.PinRecoveryRepository)), usecase.NewPinRecoveryUseCase, controller.NewPinRecoveryController)

var notificationSet = wire.NewSet(repository.NewNotification, wire.Bind(new(domain.NotificationRepository), new(*repository.NotificationRepository)), usecase.NewNotificationUseCase, controller.NewNotificationController)

var transactionSet = wire.NewSet(repository.NewTransaction, wire.Bind(new(domain.TransactionRepository), new(*repository.TransactionRepository)), usecase.NewTransactionUseCase, controller.NewTransactionController)

var topUpSet = wire.NewSet(repository.NewTopUp, wire.Bind(new(domain.TopUpRepository), new(*repository.TopUpRepository)), usecase.NewTopUpUseCase, controller.NewTopUpController)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware)
